// Task 1: Create Variables
// Write a program that stores:
// Your name
// Age
// Height
// Percentage marks
// Whether you are an intern or not
// Then print all values with their data types.
// Expected Concepts:
// String
// int
// float/double
// boolean

// let name="Ravan"
// let age=100
// let Height=17
// let Percentage=89.9
// let intern=true

// console.log(typeof(name));
// console.log(typeof(age));
// console.log(typeof(Height));
// console.log(typeof(Percentage));
// console.log(typeof(intern));



// Task 2: Student Marks Calculator
// Store marks of 5 subjects.
// Calculate:
// Total Marks
// Average Marks
// Percentage

let math=90
let hindi=46
let science=75
let biology=88
let generalScience=75

let TotalMarks=math+hindi+science+biology+generalScience
console.log("TotalMarks: ",TotalMarks);

let AverageMarks=(math+hindi+science+biology+generalScience)/5
console.log("AverageMarks: ",AverageMarks);

let percentage=(TotalMarks/500)*100
console.log("Percentage: ",percentage);