//    // let variable
    //     let a=7
    //     a=55
    //     console.log(a);

    //     {
    //         let b=10
    //     }
    //     console.log(b);  // we can not access the let variable outside the block


    //     // var variable
    //     var c=7
    //     console.log(c);

    //     {
    //         var b=10
    //     }
    //     console.log(b);  // it will give output 10 ,we can access var variable outside the block
        
// const variable

const name="Harsh"


console.log(name);  // harsh
name="Anuj kumar singh"

console.log(name);//  error


console.log("HELLO WORLD");
