// Premetive data type->String, number , Boolean, Null, Undefined, Bigint,Symbol
// Non Primitive data type->Array, Object

// string
// let name="Arjun"
// console.log(name);
// console.log(typeof(name));


// Number
// let num=45.6
// console.log(num);
// console.log(typeof(num));  

// boolean
// let pass=true
// console.log(pass);

// undefined
// let name;
// console.log(name);
// console.log(typeof(name));

//Null
// let name2=null
// console.log(name2);
// console.log(typeof(name2));


// Symbol
let id=Symbol('Abhi')
let id2=Symbol('Abhi')
console.log(id);
console.log(id2);
console.log(id==id2)   // false


// big
let Bigint=54654654654654654654654654654654
console.log(Bigint);
 



